### PR TITLE
[Pathways] added Systems/Operations headers to Methodology pages

### LINKED ISSUE #1987: [Pathways] Methodology headers are missing System/Operations text
**Describe the bug**
On the Pathways/Vitals Methodology page, there are two tabs at the top. They currently do not have any text in them. They should have the text "System" and "Operations".

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

### PR DESCRIPTION
**Pull request by ayeshakhawaja**
## Description of the change

Systems/Operations headers for Idaho and North Dakota's Methodology pages on the dashboard weren't showing up, so I added them in. A little extra code had to be added to handle the case where a state doesn't have a methodology file yet.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1987 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
~E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))~

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/core/PageNavigation/PageNavigation.tsx [hunk 1]
```diff
@@ -42,6 +42,17 @@ const PageNavigation: React.FC = () => {
...
+
+  let mergePageAndMethodologyCopy = getPageCopy(currentTenantId);
+  try {
+    mergePageAndMethodologyCopy = {
+      ...getPageCopy(currentTenantId),
+      ...getMethodologyCopy(currentTenantId),
+    };
+  } catch {
+    // no methodology exists for state
+  }
```
Comment (Catacola) [inline src/core/PageNavigation/PageNavigation.tsx:54]: I think this is fine for now, but this pattern tells me we're probably throwing unnecessarily in the `getMethodologyCopy()` function. We should be able to address this with typing to ensure that `getMethodologyCopy()` always returns copy for all valid state codes.

Could you add a TODO somewhere around here referencing this task: https://github.com/Recidiviz/pulse-dashboard/issues/2016
```
// TODO(#2016): Remove try-catch once getMethodologyCopy() always returns copy
```

**Review by Catacola — COMMENTED** [review]
Thanks for getting this out! I've got a minor change and a follow-up task to add to this.
