### PR TITLE
use metrics per tenant for vitals download

### LINKED ISSUE #1175: Vitals download data - metrics specific to tenant
**Describe the bug**
Currently we are trying to generate download data sets with ALL metrics instead of metrics specific to the tenant. Use the metrics per tenant for the downloads.

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change
Uses the Tenant's metrics for Vitals data download instead of all metrics.

Also adds temp methodology for US_ID and changes the download icon.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1175

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by Catacola — APPROVED** [review]
📜

File: src/core/DownloadDataButton.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const DownloadDataButton: React.FC<PropTypes> = ({ handleOnClick }) => {
     >
       <Icon
         className="DetailsGroup__icon"
-        kind={IconSVG.Open}
+        kind={IconSVG.Download}
```
Comment (Catacola) [inline src/core/DownloadDataButton.tsx:40]: Thank you!

**Review by Catacola — APPROVED** [review]
