### PR TITLE
Fix violation count display bug in caseload table

### LINKED ISSUE #251: Handle violation counts over one digit long in caseload table
**Describe the bug**
We are assuming that the counts of number of violations of a given type are a single digit (Line 126 of src/components/charts/new_revocations/CaseTable.js), which is causing some entries in the VIOLATION RECORD column of the filtered caseload to split two-digit numbers in the middle of the number (see screenshot). Build this string splitting function so that it can handle any amount of digits in the violation count descriptions.

**To Reproduce**
1. Go to the US_MO revocations dashboard
2. Click on a circle in the 8+ column of the matrix
3. Scroll down to the Revoked individuals section
4. See that some entries are formatted like "1 3fel"

**Expected behavior**
Parse the number digits correctly.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

image

### PR DESCRIPTION
**Pull request by macfarlandian**
## Description of the change

Fixes bug in MO revocation caseload table where double-digit violation counts in the `Violation Record` column would be displayed incorrectly. 

Screen Shot 2020-03-24 at 5 24 54 PM

I factored out the offending function and added tests in the course of doing this. As part of that refactor I removed what appeared to be a reimplementation of the `Array.indexOf` method because I couldn't really see why it was needed ... but if there was a good reason that I missed please slap me

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #251

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Lint rules pass locally
- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jessex** [comment]
@macfarlandian, heads up: the template is a bit misleading. You need to remote the block quote and the square brackets for the related issue to get it to auto-close when merged. I updated it for you, so you can see what it should look like!

File: src/components/charts/new_revocations/CaseTable.js [hunk 1]
```diff
@@ -107,32 +105,6 @@ const CaseTable = (props) => {
     return <td style={unknownStyle}>{nullSafeLabel(label)}</td>;
   };
 
-  const indexOf = (element, array) => {
```
Comment (jessex) [inline src/components/charts/new_revocations/CaseTable.js]: For the life of me, I don't know what happened here. 😬
