### PR TITLE
Fix nested filter component for admission type

### LINKED ISSUE #623: Update nested filter component
**What needs to be done? Why does it need to be done?**
We currently have an Admission Type nested filter, and will soon be turning our District filter into a nested filter which to include district sub-offices.

The functionality is as follows: 
- The filter will have "All" selected as the default. 
- If the user selects the parent (e.g., 01 - ), all of the nested children will also be checked.
- If the user selects a nested child (e.g., Specialized), the nested child will be checked, and the parent will have a (-) in the checkbox.
- If the user then clicks the (-), the parent will be checked, and all of the nested children will be checked.
- If the user then clicks "All", "All" will be checked and everything else will be unchecked.

**Additional context**
See [here](https://public.tableau.com/views/HierarchicalSelections/2_BarsTreemap?:language=en&:display_count=y&:origin=viz_share_link) for similar nested filter functionality.

### PR DESCRIPTION
**Pull request by daschi**
## Description of the change

This PR updates the nested filter component to include the following fixes:

- "All" is the default value for the admission type filter 
- Fixed spacing for the grouped filter options
- When a group is partially selected, show a partially selected checkbox

Currently deployed to staging for QA on the PA dashboard.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #623

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/components/Revocations.js [hunk 1]
```diff
@@ -99,7 +99,7 @@ const Revocations = () => {
 
       <div className="bgc-white p-20 m-20">
         <ErrorBoundary>
-          <RevocationsOverTime />
+          <RevocationsOverTime timeDescription={timeDescription} />
```
Comment (jovergaag) [inline src/components/Revocations.js:102]: Maybe we should just put the `timeDescription` in the `FiltersStore`

**Review by jovergaag — APPROVED** [review]
Beautiful

File: src/components/Revocations.js (hunk 1 above)
Comment (daschi) [reply src/components/Revocations.js:102]: Hmm yeah maybe..it is very presentational at the moment but that doesn't mean it couldn't live in a store. Maybe it would make sense to put it as part of the `BaseDataStore` since it is shared across all the charts.
