### PR TITLE
Fixes response payload empty bug

### LINKED ISSUE #913: Error: Response payload for file revocations_matrix_distribution_by_district is empty
endpoint/file mismatch

Sentry Issue: [RECIDIVIZ-PULSE-DASHBOARD-5Z](https://sentry.io/organizations/recidiviz-inc/issues/2274428507/?referrer=github_integration)

```
Error: Response payload for file revocations_matrix_distribution_by_district is empty
  at parseResponseByFileFormat (api/metrics/fileParser.js:38:11)
  at call (RootStore/DataStore/BaseDataStore.js:202:22)
  at executeAction (../../src/core/action.ts:65:16)
  at action (../../src/core/action.ts:46:16)
  at s (../../src/api/flow.ts:53:31)
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

We have a bug where an error is thrown: `Response payload for file revocations_matrix_distribution_by_district is empty`. It turns out that this was happening when the user switches charts before a data fetch finishes, so `this.file` has changed and the response payload no longer matches the `BaseDataStore` file. This sets the filename as constant so that the response payload can be accessed with the same metric filename.

I was able to reproduce this with better logging to display the issue:
Screen Shot 2021-03-17 at 5 55 55 PM

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #913

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/RootStore/DataStore/BaseDataStore.js [hunk 1]
```diff
@@ -201,7 +203,7 @@ export default class BaseDataStore {
       );
       this.apiData = parseResponseByFileFormat(
         responseData,
-        this.file,
```
Comment (Catacola) [inline src/RootStore/DataStore/BaseDataStore.js:204]: [Insert Abbot and Costello bit about `this` never being `this` but sometimes being `that`]

**Review by Catacola — APPROVED** [review]
