### PR TITLE
[Compliant Reporting] Flatten `currentOffenses`, change `reaction()` depdendencies

### LINKED ISSUE #1791: [Compliant Reporting] Offense type inputs reset when editing consecutive inputs quickly
**Describe the bug**

**To Reproduce**
1. Open a compliant reporting form
2. Edit an offense input
3. Within the subsequent 2 seconds, edit another offense input
4. The most recently edited input value is set to what it was prior to editing

**Expected behavior**
The most recently edited input value remains the same

### PR DESCRIPTION
**Pull request by ohaibbq**
## Description of the change
Destructures `currentOffenses` into separate fields on the `TransformedCompliantReportingReferralData`. This ensures that the inputs do not depend on the same fields (`.currentOffenses`) and as a result do not re-render when one of the other 4 inputs do.

Additionally, we only update the `Client` when updating Firestore.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1791

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/PracticesStore/Client.ts [hunk 1]
```diff
@@ -314,32 +315,15 @@ export class Client {
...
-        ],
-      };
-    }, {});
-
-    return {
-      ...this.prefilledCompliantReferralForm,
-      ...draft,
-    };
-  }
-
```
Comment (ohaibbq) [inline src/PracticesStore/Client.ts:335]: This was unnecessary!

**Review by Catacola — APPROVED** [review]
This looks fine to me, but I'm not the biggest mobx expert.

**Review by macfarlandian — APPROVED** [review]
