### PR TITLE
Process restrictedAccess fetch results after caching

### LINKED ISSUE #729: Cache the fetch response rather than the processed response for restrictedAccess endpoint
**Describe the bug**
We are caching the already processed result of the restrictedAccess endpoint, instead of the full file contents. Change it so that the full file contents are cached rather than the single restricted user record.

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

We were caching the already processed result of the restrictedAccess endpoint, instead of the full file contents. This adds a new `processAndRespond` callback to process the cached value before responding.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #729

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: server/core/filterRestrictedAccessEmails.js [hunk 1]
```diff
@@ -15,22 +15,15 @@
...
-  stateCode,
-  metricType,
-  file,
-  isDemo,
-  userEmail
-) {
-  return fetchMetrics(stateCode, metricType, file, isDemo).then((result) => {
+function filterRestrictedAccessEmails(userEmail, file) {
+  return (result) => {
     const restrictedEmails = result[file];
```
Comment (daschi) [inline server/core/filterRestrictedAccessEmails.js:25]: This might throw if result is `null`. It's kind of repetitive but this is what I did to handle that:

```
function processAndRespond(responderFn, processResultsFn) {
  return (err, data) => {
    if (data) {
      responderFn(null, processResultsFn(data));
    } else {
      responderFn(err, null);
    }
  };
}
```

**Review by daschi — APPROVED** [review]
