### PR TITLE
[Security] Gate API requests by state code

### LINKED ISSUE #1227: [Pen Test Finding] Fix authorization bug allowing users to access other state's data
**Describe the bug**
Users are able to copy an auth token into an API request for a state that they are not authorized to view, and receive the other state's data. 

For more details, see the [Cobalt finding](https://app.cobalt.io/recidiviz/pulse-dashboard-and-case-triage-application-august-2021-pt7441/findings/4)

**To Reproduce**

**Expected behavior**

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

### PR DESCRIPTION
**Pull request by Catacola**
## Description of the change

This PR adds validation to all routes of the form `/api/:stateCode/*/` (state_code being of the form us_xx) to ensure that the requester has the same state_code in their `app_metadata` from Auth0 (or is a Recidiviz user).

There is now an explicit list of routes which don't get their jwt validated and processed. All other routes (even those not of the form above) will get checked for a valid jwt by default.

Beyond the unit tests below, I tested by exploring the entire site and by curling unprotected routes.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)

## Related issues

Closes #1227 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: server/app.js [hunk 1]
```diff
@@ -115,10 +124,18 @@ function errorHandler(err, _req, res, next) {
   }
 }
 
-if (isDemoMode) {
-  checkJwt = (req, res, next) => {
-    next();
-  };
+if (!isDemoMode) {
```
Comment (Catacola) [inline server/app.js:127]: @jovergaag From your demo branch, I am under the impression that this is set for local demo mode but not deployed demo mode so these checks will be enabled for the pen testers when they retest. Please correct me if I'm wrong.

File: server/app.js [hunk 2]
```diff
@@ -24,16 +24,25 @@ const multer = require("multer");
...
+const { validateStateCode } = require("./utils/validateStateCode");
 
 const app = express();
 
 const upload = multer();
 
+const unprotectedRoutes = [
+  "/api/demoUser",
+  "/_ah/warmup",
+  "/api/:stateCode/:metricType/refreshCache",
```
Comment (jessex) [inline server/app.js:42]: Why is this one "unprotected?" Is there something else happening to ensure only admins can call it?

File: server/utils/validateStateCode.js [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+ */
+
+const { pathToRegexp } = require("path-to-regexp");
+
+const { getAppMetadata } = require("./getAppMetadata");
+
+const validateStateCode = (exemptRoutes) => {
+  return (req, res, next) => {
+    const matchingRoutes = exemptRoutes.filter(
+      (route) => pathToRegexp(route).exec(req.originalUrl) !== null
```
Comment (jessex) [inline server/utils/validateStateCode.js:28]: This is case-insensitive, I presume?

File: server/utils/validateStateCode.js [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+    if (matchingRoutes.length > 0) {
+      next();
+      return;
+    }
+
+    const reqStateCode = req.params.stateCode.toLowerCase();
+
+    // only filter on state codes (us_xx)
+    if (/us_[a-z][a-z]/.exec(reqStateCode) === null) {
```
Comment (jessex) [inline server/utils/validateStateCode.js:39]: Why is it that there is separate treatment for "exempted routes" and routes without stateCode in the path? Why can't the latter be explicitly listed in the former? The upside to that is it should make it so that if someone in the future mistakenly adds a route without stateCode when they meant to include stateCode, it would mean that instead of just letting requests silently next their way through, it would fail at dev time, because presumably we'd have some sort of test that ensures all routes either have stateCode or are exempted.

**Review by jessex — CHANGES_REQUESTED** [review]
Thank you for this, @Catacola ! Just a few questions from me.

File: server/utils/validateStateCode.js [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+      next();
+      return;
+    }
+
+    const metadata = getAppMetadata(req);
+    let userStateCode = metadata.state_code || "";
+    userStateCode = userStateCode.toLowerCase();
+
+    if (userStateCode === "recidiviz" || userStateCode === reqStateCode) {
```
Comment (jovergaag) [inline server/utils/validateStateCode.js:48]: CSG users have a `lantern` state code, which should allow access to US_PA and US_MO.

File: server/app.js [hunk 6]
```diff
@@ -24,16 +24,25 @@ const multer = require("multer");
...
+  "/file/:name",
```
Comment (jovergaag) [inline server/app.js:43]: I think we need to add `/api/generateFileLink` to this list.

File: server/utils/validateStateCode.js [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+    if (matchingRoutes.length > 0) {
+      next();
+      return;
+    }
+
+    const reqStateCode = req.params.stateCode.toLowerCase();
+
+    // only filter on state codes (us_xx)
+    if (/us_[a-z][a-z]/.exec(reqStateCode) === null) {
+      next();
```
Comment (jovergaag) [inline server/utils/validateStateCode.js:40]: All of our routes that are protected are formatted as `/api/:stateCode/*`. Do we want to call next here if the state code is not formatted properly? I would think we would want to send a 400?

File: server/utils/__tests__/validateStateCode.test.js [hunk 8]
```diff
@@ -0,0 +1,109 @@
...
+  expect(resp.sendStatus.mock.calls.length).toBe(1);
+  expect(resp.sendStatus.mock.calls[0][0]).toBe(401);
+};
+
+describe("validateStateCode", () => {
+  beforeEach(() => {
+    jest.resetModules();
+  });
+
+  it("should call next() if stateCode in request matches state code in app_metadata", () => {
```
Comment (jovergaag) [inline server/utils/__tests__/validateStateCode.test.js:68]: We may want to add a test with an upper case state code just to be safe.

**Review by jovergaag — CHANGES_REQUESTED** [review]
This looks awesome! Just a few comments.

File: server/app.js (hunk 6 above)
Comment (jovergaag) [reply server/app.js:43]: Or maybe not? We want it to be "protected" in the sense that we are using `checkJwt` but not validating the state code. Do we need to differentiate between the two?

File: server/utils/validateStateCode.js (hunk 4 above)
Comment (jovergaag) [reply server/utils/validateStateCode.js:39]: @jessex I agree. The only route as this is written that is not "unprotected" but does not include stateCode is `/api/generateFileLink`. I think it makes sense to add that to the exempted list and add the `checkJwt` back into it.

Maybe the exempted list can be renamed to `routesWithoutStateCode` and we add the `checkJwt` back into each route individually to be very explicit. 

Since @Catacola is OOO today, I'll push up a commit to see what you think.

File: server/utils/validateStateCode.js (hunk 3 above)
Comment (jovergaag) [reply server/utils/validateStateCode.js:29]: Yes. I added some tests to confirm that.

**Comment by jovergaag** [comment]
@jessex @daschi This is ready for another look!

**Review by daschi — APPROVED** [review]
🔒

File: server/app.js [hunk 9]
```diff
@@ -124,18 +116,10 @@ function errorHandler(err, _req, res, next) {
...
-  app.use(
-    checkJwt.unless({
-      path: unprotectedRoutes.map((r) => pathToRegexp(r)),
-    })
-  );
-
-  // Verify that the user has access to state-specific date
-  // for all state-specific routes
-  app.use("/api/:stateCode/", validateStateCode(unprotectedRoutes));
+if (isDemoMode) {
```
Comment (jessex) [inline server/app.js]: Sorry if I missed this, but doesn't this mean that in both local mode and in demo mode there won't be any stateCode validation, so when we deploy this and ask the pin testers to retest they'll just find the same vulnerability has before?

File: server/app.js [hunk 10]
```diff
@@ -157,6 +159,21 @@ app.get("/_ah/warmup", () => {
...
+  "/api/demoUser",
+  "/_ah/warmup",
+  "/api/:stateCode/:metricType/refreshCache",
+  "/file/:name",
+  "/api/generateFileLink",
+];
+
+// Verify that the user has access to state-specific date
+// for all state-specific routes
+app.use(
```
Comment (jessex) [inline server/app.js:172]: Will this apply even in demo mode above?

**Review by jessex — COMMENTED** [review]
One question!

File: server/app.js (hunk 9 above)
Comment (jovergaag) [reply server/app.js]: In the deployed demo app, `isDemoMode` currently resolves to `false`. I know its confusing, I was in the middle of clearing up the terminology and ENV vars and in the code when the Vitals flurry started, so it's still in this in between state. I've got a commit with this DEMO -> OFFLINE name change that I can add here to make it more clear, but I lean towards keeping those two changes isolated since they are such big changes.

The new ENV vars are in `1Password` if you wanted to look at them. In the deployed demo app environment, `IS_DEMO = false`

I did realize yesterday evening that moving the state code validation middleware to the bottom of the file, means that it was never being hit, so the commit from today fixes that. I moved it back up and the `server.test.js` now reflects the new error message from the custom middleware state code validation.

Comment (jessex) [reply server/app.js]: Thanks for the explanation! Yes let's keep those changes isolated from one another. I see that this should work as expected now with the latest commit and test coverage.

**Review by jessex — APPROVED** [review]
I think we're good to go now! Thanks so much, @jovergaag and @Catacola!

File: server/app.js (hunk 10 above)
Comment (jovergaag) [reply server/app.js]: Yes. That `isDemoMode` block only overrides the `checkJwt` middleware since in the tests and in local mode we are not authorizing users. The request will fall through to the rest of the middleware and routes in demo mode (which, until I can change the name, is actually local/test mode). In the deployed demo app, `isDemoMode = false` so the the user will be authorized on every route that specifies `checkJwt`

I really apologize for the confusion here. I was trying to do the demo mode transition in steps and got pulled away before having the chance to clean everything up.

**Review by jovergaag — APPROVED** [review]
