### PR TITLE
Fix vertical alignment of filter chip - label and delete button

### LINKED ISSUE #595: Filter chips are vertically misaligned
**What needs to be done? Why does it need to be done?**
The text in the filter chips in the Lantern dashboard (both MO and PA) do not appear to be vertically centered - text looks slightly higher than center in these examples:

Note, in this second example, the vertical offset changes when the page scrolled all the way to the top. When I scroll down and the additional filter bar changes orientation, the text appears more center-aligned (the "X" appears slightly closer to the top, but is less severe than the above screenshots):

**Additional context**
I'm think I started noticing this maybe 10/27 or 10/28 before training. It didn't appear like that during other QA rounds, otherwise I'm pretty sure I would have noticed.

This is not beta exit blocking, and can be prioritized alongside any UI / tech debt tasks. Placing in 11/2 for discussion purposes.

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

The filter chips were vertically misaligned. This was the case in the 'Additional Filters' filter bar as well as the filter buttons in the revocations by district chart.

The chips after the fix:
Screen Shot 2020-11-03 at 1 16 40 PM
Screen Shot 2020-11-03 at 1 41 31 PM
Screen Shot 2020-11-03 at 1 41 36 PM

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #595

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jovergaag** [comment]
@sychang "am i ok"? :)

**Comment by sychang** [comment]
You are so ok!

File: src/components/charts/new_revocations/ToggleBar/ViolationFilter.js [hunk 1]
```diff
@@ -50,6 +52,7 @@ const ViolationFilter = ({ reportedViolations, violationType, onClick }) => {
       >
         <Chip
           label={formattedMatrixFilters}
+          className={cn({ "Chip--shrinking": isTopBarShrinking })}
```
Comment (macfarlandian) [inline src/components/charts/new_revocations/ToggleBar/ViolationFilter.js:55]: what's the reasoning behind moving this logic out here? it kind of seems to me that it was better off encapsulated within the `Chip` component rather than the parent having to know it needs to apply this classname. Especially since `Chip` is still conditionally applying other classnames to itself based on props

**Review by macfarlandian — CHANGES_REQUESTED** [review]

File: src/components/charts/new_revocations/ToggleBar/ViolationFilter.js (hunk 1 above)
Comment (jovergaag) [reply src/components/charts/new_revocations/ToggleBar/ViolationFilter.js:55]: There is only one Chip on the page (out of 15ish) that shrinks based on the scroll of the page. Prior to this PR the other chips were shrinking but that was a bug. 

Other options are to pass a boolean into Chip that specifies whether a particular instance is shrinkable. Or shrink the Chip when it is nested under `.FilterField--shrink`. I'm not a fan of the second option. I'll push up a commit to see what the first option looks like.

Comment (jovergaag) [reply src/components/charts/new_revocations/ToggleBar/ViolationFilter.js]: @macfarlandian That is much better, good suggestion. Ready for another look.

**Review by macfarlandian — APPROVED** [review]
🎸 🎶
