### PR TITLE
fix resetFilters in the NoData component

### LINKED ISSUE #1441: [Pathways] Reset filters button doesn't refresh view
**Describe the bug**
When the "Reset Filters" button is clicked, the filter UI is updated to show that the filters were reset, but the plot is not redrawn.

Additionally, upon interacting with any of the filters, all of the others are reset to their previous states.

As of current writing, the following link should trigger a null view: https://dashboard-staging.recidiviz.org/system/prison/personLevelDetail?ageGroup=25-29%20years%20old%2C40-44%20years%20old&facility=DJRC&gender=Female&legalStatus=All

**To Reproduce**
1. Go to https://dashboard-staging.recidiviz.org/system/prison/personLevelDetail?ageGroup=25-29%20years%20old%2C40-44%20years%20old&facility=DJRC&gender=Female&legalStatus=All
2. Click on 'Reset Filters'
3. See that the view isn't reset
4. Edit any filter
5. See the existing ones reset to their previous states.

**Expected behavior**
The plot should revert to its initial, unfiltered state.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: 
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: 
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

The"Reset filters" button in the `NoData` component was not workin because it was trying to reset the filters directly rather than resetting them via the query params. 

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1441

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/components/HydrationStatus/NoData.tsx [hunk 1]
```diff
@@ -16,17 +16,31 @@
...
+    const query = {} as Record<keyof EnabledFilters, string>;
+    [...metric.enabledFilters, ...metric.enabledMoreFilters].forEach(
+      (filterType) => {
+        query[filterType] =
+          filtersStore.filterOptions[
+            filterType as keyof PopulationFilters
+          ].defaultOption.label;
+      }
+    );
+    setQuery(query, "replace");
```
Comment (macfarlandian) [inline src/components/HydrationStatus/NoData.tsx:43]: not necessarily a blocker if this pattern is generally in use in this application, but I think it would be cleaner if the data store just handled this rather than making the components do it?

**Review by macfarlandian — APPROVED** [review]

File: src/components/HydrationStatus/NoData.tsx (hunk 1 above)
Comment (jovergaag) [reply src/components/HydrationStatus/NoData.tsx]: Dang you're fast, approved before I was able to write this comment! 

I think this was a great suggestion. To be honest, it still is kind of messy with all of our `setQuery` logic spread across a few different components. I have another branch where I'm currently working on filters, transitioning from single select to multi-select. I think I will work on the filtering logic there such that the components call `filtersStore.setFilters` and have the query set in a hook. That feels more maintainable. Thanks for calling this out.

Comment (macfarlandian) [reply src/components/HydrationStatus/NoData.tsx]: yeah i did notice that but I figured this was at least an incremental improvement so it's all good 👍🏻
