### PR TITLE
Pathways design polish

### LINKED ISSUE #1697: Pathways - design polish
**What needs to be done? Why does it need to be done?**
- [ ] Download data icon is incorrect size. Try to make the existing icon 16x16px. If that doesn't work with the icon imported from web-libraries use the icon below.
- [ ] Change the color of the highlighted bar(s) on the gold charts to #25B894
- [ ] Decrease the width of the LH Nav
- [ ] Make LH Nav icons smaller
- [ ] Change line and dot style in line graphs

[Design with red markup showing changes](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=4570%3A135)

**Additional context**
Add any other context about the task here.

### LINKED ISSUE #1718: Prior length of incarceration chart - label update
**What needs to be done? Why does it need to be done?**
Update the "0" label on the "Prior length of incarceration" chart so that the label says "Not previously incarcerated". This should still be the left most label on the x-axis.

**Additional context**
Add any other context about the task here.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

- [x] Download data icon is incorrect size. Try to make the existing icon 16x16px. If that doesn't work with the icon imported from web-libraries use the icon below.
- [x] Change the color of the highlighted bar(s) on the gold charts to #25B894
- [x] Decrease the width of the LH Nav (previous design update)
- [x] Make LH Nav icons smaller (previous design update)
- [x] Change line and dot style in line graphs
- [x] [Updated prior length of incarceration chart label

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1697 
Closes #1718 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx [hunk 1]
```diff
@@ -187,10 +188,10 @@ const VizPopulationSnapshot: React.FC<VizPopulationOverTimeProps> = ({
           style={(d: any) => {
             if (!isGeographic) {
               if (d.index === hoveredId) {
-                return { fill: styles.dataGoldDark };
+                return { fill: styles.signalHighlight };
```
Comment (jovergaag) [inline src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx:191]: After working with the designer on this for a bit, we have decided to change the highlight/hover color interaction. Instead of giving the highlighted/hovered bars a new color, let's keep them the SAME color, and just fade the other (NOT highlighted or hovered) bars by adjusting the opacity by 0.45.

Does that make sense? That way the gold chart and the green chart have the same interaction. Let me know if you have questions on this.

**Review by jovergaag — CHANGES_REQUESTED** [review]
Looking pretty good!

File: src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx (hunk 1 above)
Comment (nasaownsky) [reply src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx]: I don't know how to manage the opacity the way you specified, `fill-opacity` will make columns semi-transparent, which we don't want, I suppose. So we'll need specified colors anyway.

**Review by jovergaag — APPROVED** [review]
