### PR TITLE
[Workflows] Fix missing supervision levels for ND clients

### LINKED ISSUE #2269: Some people are missing supervision levels
Reference this [comment](https://docs.google.com/document/d/1sNhaS60nHtbrvGx7sKLZVxuP4faThvEaXIymz1WiAOY/edit?disco=AAAAel2M-ao) in bug bash doc for examples.

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

Fixes the missing supervision levels for the ND clients. 

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #2269

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/WorkflowsStore/Client.ts [hunk 1]
```diff
@@ -56,12 +56,22 @@ import { OTHER_KEY } from "./WorkflowsStore";
 
 export const UNKNOWN = "Unknown" as const;
 
-// these are the only values supported for now, limited to the Compliant Reporting flow
-type SupervisionLevel = "Medium" | "Minimum" | typeof UNKNOWN;
+type SupervisionLevel =
```
Comment (jovergaag) [inline src/WorkflowsStore/Client.ts:59]: Let me know if you think it would be helpful to maintain separate types for clients in different states. I think maintaining a single list is sufficient but am open to breaking them out.

Comment (macfarlandian) [reply src/WorkflowsStore/Client.ts:59]: no I think this is fine, no need to overcomplicate things (unless/until we get to the point where different states have conflicting mappings)

**Review by macfarlandian — APPROVED** [review]
