### PR TITLE
Fixes exports of chart images and data in the MS browsers.

### LINKED ISSUE #39: Fix broken exports in MS browsers
Exports appear to be broken in Microsoft Edge and IE11. In both, _Export Image_ appears to not even register. In the former, _Export Data_ brings up a small dialog at the bottom of the window saying the file could not be downloaded. In the latter, _Export Data_ redirects to a new tab with the json in the browser bar, escaped, producing an error.

### PR DESCRIPTION
**Pull request by jessex**
This closes #39. Replaces my artisan download code with a dedicated [library](https://github.com/rndme/download), which is how it should be.

Tested image and json exports successfully in multiple browsers in stage (and production, for the Friday morning release), including Edge and IE11.

### CODE REVIEW

File: src/components/TopBar.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ const TopBar = (props) => {
             <li className="dropdown">
               <a href="#" onClick={() => loginWithRedirect({appState: { targetUrl: "/snapshots" }})} className="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
                 <div className="peer mR-10">
-                  <i class="ti-power-off"></i>
+                  <i className="ti-power-off"></i>
```
Comment (jessex) [inline src/components/TopBar.js]: This was just something I noticed.
