### PR TITLE
[Pathways][US_TN] Fixes rounding error in rate charts, and updated methodology copy

### LINKED ISSUE #1786: Fix broken download in FE

### LINKED ISSUE #1787: Fix broken rates charts in the FE

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

Updates the rounding issue in the rate charts when the rate is < 1%, and updates the methodology copy which fixes the broken downloads.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1787 and Close #1786

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/core/models/SupervisionPopulationSnapshotMetric.ts [hunk 1]
```diff
@@ -110,12 +110,13 @@ export default class SupervisionPopulationSnapshotMetric extends PathwaysMetric<
...
+        const populationProportion =
+          (sumBy("count", dataset) * 100) / this.totalCount;
         return {
           count: sumBy("count", dataset),
-          populationProportion: (
-            (sumBy("count", dataset) * 100) /
-            this.totalCount
-          ).toFixed(),
+          populationProportion: populationProportion.toFixed(
+            populationProportion < 1 ? 2 : 0
```
Comment (danawillow) [inline src/core/models/SupervisionPopulationSnapshotMetric.ts:118]: I'm not going to block on it but it would be nice to have a test that covers this case

**Review by danawillow — APPROVED** [review]

File: src/core/models/SupervisionPopulationSnapshotMetric.ts (hunk 1 above)
Comment (jovergaag) [reply src/core/models/SupervisionPopulationSnapshotMetric.ts:118]: Yes it would be nice. In the spirit of being ready for launch I'm going to go ahead without it. But great suggestion and next time block me on it!!
