### PR TITLE
Fixes a fast-follow bug fixes after feedback sessions with program ma…

### LINKED ISSUE #169: Remove summary sentence when Admissions vs. Releases chart is in rate mode
**Describe the bug**
On the "Reincarcerations" page, the Admissions vs. Releases chart has a sentence summarizing the change in facility size for ND prisons. When in rate mode, this sentence tells you that the change in facility size has been a fraction of a person for the past month. 

Example: The ND facilities shrank by 0.47 people this month.

**To Reproduce**
1. Go to dashboard.recidiviz.org
2. Click on 'Reincarcerations'
3. Select "rates." Ensure "all" is selected in the location drop down. 
4. View "Admissions vs. Releases chart. 

**Expected behavior**
In rate mode, that sentence disappears. 
An equally valid behavior is for that sentence, in rate mode, to say "The ND facilities [shrank | grew] by 0.30 **%** this month."

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: MacOS Mohave
 - Browser [e.g. chrome, edge]: Chrome
 - Version [e.g. 22]: 79.0.3945.88

### LINKED ISSUE #171: Map view missing data for 3 years in admissions vs. releases chart
**Describe the bug**
The map view is blank in the `ADMISSIONS VERSUS RELEASES` chart when 3 years is selected. The map shows up, but there is no data populating it. 

**To Reproduce**
1. Go to the [dashboard](dashboard.recidiviz.og)
2. Change profile to North Dakota (if needed)
3. Go to `REINCARCERATIONS` page
4. Change time period to `3 years`
5. Select `map` on `ADMISSIONS VERSUS RELEASES` chart

The map is now empty of data. This is true for both counts and rates and if any county is selected. 

**Expected behavior**
The map contains data about 3 years of admissions and releases for each county. 

**Screenshots**
Screen Shot 2020-02-12 at 2 12 05 PM

### LINKED ISSUE #172: Add officer labels to x axis, download for revocations by officer chart when all P&P offices selected
**Describe the bug**
The revocations by officer chart does not show officer ID labels when all offices are selected. The download thus also does not include officer ID labels.

**To Reproduce**
1. Go to [the dashboard](dashboard.recidiviz.org)
2. Click on `REVOCATIONS`
3. Make sure P&P office selection is `All`
4. Click `Export` -> `Export as image`
5. Open exported image and see that one can't tell which line belongs to which officer 

**Expected behavior**
The downloaded image contains Officer ID #s on the x axis. Ideally, the x axis also contains officer IDs when all counties are selected in very small font. 

If it isn't possible to have officer IDs showing without terrible overcrowding when all offices are selected, add an alert icon when all districts selected saying "Exporting this as an image will not include officer IDs unless a specific P&P office is selected from the Explore bar"

### PR DESCRIPTION
**Pull request by jessex**
## Description of the change

This fixes all 3 bugs from the issues listed below. For #172, it was determined that there was no way to cleanly display all officer id labels along the x-axis when no office is selected, so we added an alert icon in that case to explain that exports will not have labels until an office is selected.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #169 
Closes #171 
Closes #172 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Lint rules pass locally
- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/components/charts/GeoViewTimeChart.js [hunk 1]
```diff
@@ -369,12 +369,12 @@ class GeoViewTimeChart extends Component {
             denominator = totalDenominatorByMetricPeriod[metricPeriodMonths];
           }
 
-          if (numerator === 0 || (denominator === 0 && denominatorKeys.length > 0)) {
+          if (numerator === 0 && (denominator === 0 && denominatorKeys.length > 0)) {
```
Comment (jessex) [inline src/components/charts/GeoViewTimeChart.js]: This was causing the 3-year data miss for Admissions vs Releases. It happened to be the case that the denominator key values for this chart all had values of 0 when metric period months = 36, so this logic would short-circuit setting any data values for the office for that metric period, including the valid numerator. So we altered this check and the rate calculation check to ensure we always capture data that we can capture.

File: src/components/charts/revocations/RevocationCountByOfficer.js [hunk 2]
```diff
@@ -293,6 +293,7 @@ const RevocationCountByOfficer = (props) => {
             stacked: true,
             ticks: {
               display: displayOfficerIds,
+              autoSkip: false,
```
Comment (jessex) [inline src/components/charts/revocations/RevocationCountByOfficer.js]: This ensures that when we have selected an office with a relatively large number of officers, we will still display all of them and not skip some by ChartJS' algorithm.
