### PR TITLE
UI Fixes from final QA round

### LINKED ISSUE #574: 10/25/20 PA QA
**What needs to be done? Why does it need to be done?**
This ticket captures all UI bugs found during the 10/25/20 QA before PA launch training on 10/29.

3 small bugs from QA of new law violation change, detailed in this [sprint planning doc](https://docs.google.com/document/d/1o1mJD0Cbb8B9M-Dt10uWkbPbhzbnSNN3XO9_gQ4bEmQ/edit) and repeated here:

1. P0: Methodology (Screenshots in doc)
- For risk level chart, “level” is missing an “l”
- For admitted individuals table in the “last recommendation” section, “PRison” has a typo capitalization.
- Grammatical suggestions from CSG's comms team in suggest mode in the methodology doc: https://docs.google.com/document/d/1V-HTYgfklb-VmsYmXmzMCBiNa1CUp4QHbseGl1M2VC8/edit?ts=5f96d032#

2. P0: For PA only, on the race middle chart, change "African American" to "Black" and "Caucasian" to "White" so it matches PA's vocabulary, as seen in reports like this: https://www.cor.pa.gov/About%20Us/Statistics/Documents/Budget%20Documents/2019%20Inmate%20Profile.pdf

3. P1: There appear to be no Pacific Islanders in PA because there are 0 admitted in a 3 year period. If that is true, remove the Pacific Islander bar from the race chart for PA only.

4. P1: When any “1 violation” bubble is selected, the "additional filters" bar emerges and says "1 violations," which is grammatically incorrect. It should say "1 violation" when any 1 violation bubble is selected (but remain plural when any other number is selected)

5. P1: The additional filter bar has a glitchy transition when scrolling up and down (video of [screencapture](https://drive.google.com/file/d/1WLWPgbLuRQk5Sc3gW_C4AoJeOTEJrK-A/view?usp=sharing)).

6. P2: On the email verification page, the following text is missing a space after period. "If you have reached this page by mistake, please try to log in again.If you are still having trouble, please reach out to Recidiviz Support."

**Additional context**
P0 is launch blocking, P1-2 are not strictly launch-blocking.

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change
Serena found a few remaining issues during her final (maybe?) round, along with additional methodology updates from CSG. 
1. Methodology updates
2. Update Race labels for PA: "African American" -> "Black", "Caucasian" -> "White"
3. Remove "Pacific Islander" from the Race charts for both MO and PA since that data is not being collected
4. Pluralize the "Violation Filter" bubble labels.
5. Fix styling on violation filter bubbles when scrolled all the way to the top - bubble should not be full width
6. Fix animation on scroll when filter bars change to `topBarIsShrinking` mode
7. Fix typo in verify page

Details can be found in the issue #574

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #574

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/hooks/usePageLayout.js [hunk 1]
```diff
@@ -15,20 +15,28 @@
...
 // =============================================================================
 
-import { useLayoutEffect, useRef, useState } from "react";
-
-const useTopBarShrinking = () => {
-  const [isTopBarShrinking, setIsTopBarShrinking] = useState(false);
+import { useLayoutEffect, useRef } from "react";
+import { usePageState, usePageDispatch } from "../contexts/PageContext";
 
+const usePageLayout = () => {
```
Comment (jovergaag) [inline src/hooks/usePageLayout.js:21]: We were previously keeping a boolean here, `isTopBarShrinking`, but the animation when scrolling down the page when the `ViolationFilter` bar was active was funky because the timing of the different filter renders and updates to this boolean sourced from many different components. So I moved this to a context such that there is one event that changes the boolean and all components can then access that single value.

File: src/views/tenants/utils/us_pa_methodology.js [hunk 2]
```diff
@@ -23,105 +23,106 @@ export const PA_METHODOLOGY = {
...
+      body: `Counts include all people who were admitted to SCIs from parole. This includes people on parole who were admitted for non-revocation sanctions and those who were admitted for revocation. Counts do not include (1) people with Parole Violator Pending status who have been detained pending a revocation hearing but have not been legally revoked; (2) people who are serving a State Indeterminate Punishment sentence; (3) placements in Parole Violator Centers. This chart (like all charts on the page) will automatically repopulate to match whatever filter(s) the user has selected. For example, if the user has selected “District 2” from the drop-down menus at the top of the screen, this chart will automatically update to include only people from District 2.
```
Comment (jessex) [inline src/views/tenants/utils/us_pa_methodology.js:100]: I think this is a mistake? Looking at the methodology doc listed in #574, it doesn't include this "Counts include all..." line for the "Filtering by violation history" section. It only exists under the "Who is included" section.

File: src/views/tenants/utils/us_pa_methodology.js [hunk 3]
```diff
@@ -23,105 +23,106 @@ export const PA_METHODOLOGY = {
...
... with the same sex and risk level. For example, if the user selected the low technical row on the plot, the chart would show for men and women overall, and for each risk level, the number of people admitted whose most serious violation was a low technical, divided by the total number of people on supervision whose most serious violation was a low technical, regardless of whether they were admitted. Continuing with this example, if a user hovers over the low-risk column for women, the numerator would be all low-risk women admitted for a low technical violation and the denominator would be all low-risk women who committed a low technical violation, whether they were admitted to a DOC facility or not. Comparing these percentages will indicate whether admission practices differ between men and women. That is, whether men are more (or less) frequently admitted compared to women with the same risk level and violation history. For people who have not been admitted, the most serious violation is identified by considering all violations reported within one year from either the current date (if the person is still on supervision) or the date that the person was discharged from supervision.`,
```
Comment (jessex) [inline src/views/tenants/utils/us_pa_methodology.js:101]: Similarly, this addition of the "Filtering by violation history" prefix shouldn't be here. That's just the header, which is already up on L99.

**Review by jessex — CHANGES_REQUESTED** [review]
Great work, @jovergaag! Just some potential copy issues in the PA methodology text from the first commit. Also, in local testing, it _looks to me_ like we no longer have a smooth transition from wide to thin on the scroll down the page. _Last I checked_, that thinning was a gradual animation, but now it just instantly clicks back and forth. However, I just checked production and it looks like that's how it's currently behaving in prod, too, so I don't know when that functionality regressed, or if it was removed intentionally. Do you have any insight into that? If not, we should probably file a ticket for it.

File: src/views/tenants/utils/us_pa_methodology.js (hunk 2 above)
Comment (jovergaag) [reply src/views/tenants/utils/us_pa_methodology.js:100]: Thanks. I've done these copy updates too many times, starting to move too quickly, le sigh.

**Comment by jovergaag** [comment]
@jessex I don't remember the smooth transition, if there was a regression I am not quite sure when it would have happened. I'll make an issue to add it back in and ask @sychang for input on requirements.

**Review by jessex — APPROVED** [review]
Thanks, @jovergaag! 👏

**Comment by sychang** [comment]
Thank you for all of this! +10000 on so many rounds methodology changes and major shoutout for helping iterate on it so quickly.

Not super helpful but I also noticed the transition / thinning on the additional filters bar looked a bit different than I remember it but I also couldn't pin exactly how and when it changed. Happy to discuss later, definitely not launch-blocking or high-pri here.

**Comment by jovergaag** [comment]
@sychang It's all part of the process!

Lets sync up tomorrow on the additional filters transition.

**Comment by sychang** [comment]
Chatting offline with Jen, but for posterity, here's a screencapture of the filter bar transition in demo mode, which is indeed a bit different for both the top filter bar and the additional filters: https://drive.google.com/file/d/1REE81PaTOE7Ecn9cFtYI7E32A_x_gZzi/view?usp=sharing
