### PR TITLE
Fixes the sticky top elements in IE11 and Safari.

### LINKED ISSUE #163: Make explore bar sticky-top work in IE11
**Describe the bug**
The Explore Bar, the bar with the different toggles for filtering and exploring metrics by different dimensions, is set to stick to the top of its viewport even when scrolling. The current implementation isn't working in IE11 on Windows.

**To Reproduce**
1. Go to any view for a non-Lantern state
2. Scroll down the page until the explore bar is no longer in view
3. See that the bar is no longer visible, while it should have stuck to the top of the view.

**Expected behavior**
The bar should have remained visible, directly below the top navbar.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: Windows
 - Browser [e.g. chrome, edge]: IE11
 - Version [e.g. 22]: Any

### PR DESCRIPTION
**Pull request by jessex**
## Description of the change

This ensures that the sticky top components, the toggle bars, work in IE11 and Safari, in addition to the existing support in Chrome, Firefox, Edge, etc.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #163 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Lint rules pass locally
- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/components/toggles/ToggleBar.js [hunk 1]
```diff
@@ -16,6 +16,7 @@
 // =============================================================================
 
 import React from 'react';
+import Sticky from 'react-sticky-fill';
```
Comment (jjdressel11) [inline src/components/toggles/ToggleBar.js]: I really thought that "sticky" was your word!

Comment (jessex) [reply src/components/toggles/ToggleBar.js]: It is--I invented the sticky top concept back in my days at Xerox PARC.
